-- method 1:--
SELECT NAME FROM STUDENTS WHERE MARKS > 75 ORDER BY 
SUBSTR(NAME, LENGTH(NAME)-2, 3), ID; 

-- method 2:--
SELECT Name 
FROM STUDENTS 
WHERE Marks > 75 
ORDER BY RIGHT(Name, 3), ID ASC;


-- method3:-
SELECT Name 
FROM STUDENTS 
WHERE Marks > 75 
ORDER BY SUBSTR(Name, LENGTH(Name)-2), ID ASC;
-- or 
SELECT Name 
FROM STUDENTS 
WHERE Marks > 75 
ORDER BY SUBSTR(Name, LENGTH(Name)-2), ID;